version: '3.8'

services:
  backend:
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cacheme
    depends_on:
      - mongo

  frontend:
    image: nginx:latest
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./nginx_cache:/data/nginx/cache 
      - ./nginx_cache:/data/nginx/cache:rw  # Ensure read-write access
    depends_on:
      - backend
  
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-products.js:/docker-entrypoint-initdb.d/init-products.js:ro

volumes:
  mongo-data: